services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./data:/home/jovyan/work/data
      - ./notebooks:/home/jovyan/work/notebooks
      - ./models:/home/jovyan/work/models
